Server:
  Port: 5555
Store:
  Hat:
    Price: 200.00
    Currency: USD
  Shoes:
    Price: 450.00
    Currency: USD
  Pant:
    Price: 325.00
    Currency: USD
  Shirt:
    Price: 500.00
    Currency: USD
Logging:
  Path: ../logs/logs.log
  LogLevel: debug
  Logger: zerologger